name: Auraton-Tests

on:
  push:
    branches:
      - master
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  TESTS_SOURCE_FOLDER: ${{github.workspace}}/tests
  SOURCE_FOLDER: ${{github.workspace}}
  BUILD_FOLDER: build_ninja  
  
jobs:
  Auraton-Unit-Tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Get latest CMake and ninja
      uses: lukka/get-cmake@latest
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/$BUILD_FOLDER  
    - name: Generate
      run: |
        cd ${{github.workspace}}/$BUILD_FOLDER
        cmake -G Ninja $TESTS_SOURCE_FOLDER
    - name: Build
      run: |
        cd ${{github.workspace}}/$BUILD_FOLDER
        ninja
    - name: Test
      run: |
        cd ${{github.workspace}}/$BUILD_FOLDER
        ninja test
        
  Auraton-Test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Get latest CMake and ninja
      uses: lukka/get-cmake@latest
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/$BUILD_FOLDER  
    - name: Generate
      run: |
        cd ${{github.workspace}}/$BUILD_FOLDER
        cmake -G Ninja $SOURCE_FOLDER
    - name: Build
      run: |
        cd ${{github.workspace}}/$BUILD_FOLDER
        ninja
    - name: Run
      run: |
        cd ${{github.workspace}}/$BUILD_FOLDER
        echo q | ./auraton
