name: Auraton-Tests

on:
  push:
    branches:
      - test_branch
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  TESTS_SOURCE_FOLDER: ${{github.workspace}}/tests
  SOURCE_FOLDER: ${{github.workspace}}
  BUILD_FOLDER: build_ninja  
  
jobs:
  Auraton-Unit-Tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout reposistory
      uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
      with:
        remote: true
    - name: Get latest CMake and ninja
      uses: lukka/get-cmake@latest
    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}/$BUILD_FOLDER  
    - name: Generate
      run: |
        cd ${{github.workspace}}/$BUILD_FOLDER
        cmake -G Ninja --config $BUILD_TYPE $TESTS_SOURCE_FOLDER
    - name: Build
      run: |
        cd ${{github.workspace}}/$BUILD_FOLDER
        ninja
    - name: Test
      run: |
        cd ${{github.workspace}}/$BUILD_FOLDER
        ninja test
