name: Auraton-Unit-Tests

on:
  push:
    branches:
      - test_branch
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_FOLDER: build_ninja  
  
jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - name: Checkout reposistory
      uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
      with:
        remote: true
    - name: Checkout Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}/$BUILD_FOLDER
      
    - name: Generate
      run: |
        cd ${{github.workspace}}/$BUILD_FOLDER
        cmake -G Ninja --config $BUILD_TYPE ${{github.workspace}}

    - name: Build
      run: |
        cd ${{github.workspace}}/$BUILD_FOLDER
        ninja
        
    - name: Dupa
      run: |
        cd ${{github.workspace}}/$BUILD_FOLDER
        ninja -t deps
        ninja help
        
    - name: Test
      run: |
        cd ${{github.workspace}}/$BUILD_FOLDER
        ninja test
